[package]
name = "relocate"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
derive_more = { version = "2.1.1", features = ["full"] }
hex = "0.4.3"
pretty-hex = "0.4.1"

[[bin]]
name = "relocate"
path = "src/main.rs"
