[package]
name = "relocate-midi"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
derive_more.workspace = true
hex.workspace = true
pretty-hex.workspace = true
